### PR TITLE
bar -> \bar

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@star1327p @merliseclyde @rundel @mine-cetinkaya-rundel   Quick poke -- more characters in this note than in the PR -- when reading the (nice!) book online I saw one "bar" in a formula in chapter six.  This just adds the missing `\` in front of `bar`.  When I submitted the PR the repo was in flux for an R package issue (it seems) so I just rebased.  Should be fine now.

**Comment by eddelbuettel** [comment]
Hm.  But now the changeset is eight files because of the rebase.  Anyway -- that is all in `master`; you can also just cherrypick [this commit](https://github.com/StatsWithR/book/pull/62/commits/14da936d5cae2787e12c9e2d22352cc5e2abf81e) which is the one char change.  Or close it and edit by hand. Whatever works.

**Comment by merliseclyde** [comment]
Thanks!  missed the earlier PR.  Fixed.

**Comment by eddelbuettel** [comment]
Hm, you closed but didn't merge.

**Pull request closed without merging**
